apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: sachinyaduvanshi7/products
          resources:
            limits:
              memory: "356Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
