apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: products
    app.kubernetes.io/instance: products-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - image: 597088043946.dkr.ecr.ap-south-1.amazonaws.com/products:latest
          imagePullPolicy: Always
          name: products
          ports:
            - containerPort: 3002
