apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: products
    app.kubernetes.io/instance: products-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: products
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
